using System.Collections.Generic;
using UnityEngine;

public static class CyberSecurityQuiz
{
    public class QuizQuestion
    {
        public string Question { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
    }

    private static readonly List<QuizQuestion> quizQuestions = new()
    {
        new QuizQuestion { Question = "What is phishing?", Option1 = "A cyber-attack to steal information", Option2 = "A type of fishing sport" },
        new QuizQuestion { Question = "What does HTTPS stand for?", Option1 = "HyperText Transfer Protocol Secure", Option2 = "High Transfer Text Security" },
        new QuizQuestion { Question = "What is a strong password?", Option1 = "A mix of letters, numbers, and symbols", Option2 = "Your name and birthdate" },
        new QuizQuestion { Question = "What is malware?", Option1 = "Malicious software", Option2 = "Hardware malfunction" },
        new QuizQuestion { Question = "What is a firewall?", Option1 = "A network security system", Option2 = "A physical wall" },
        new QuizQuestion { Question = "What is two-factor authentication?", Option1 = "Two security layers for login", Option2 = "Two accounts for one user" },
        new QuizQuestion { Question = "What does a VPN do?", Option1 = "Encrypts your internet connection", Option2 = "Boosts internet speed" },
        new QuizQuestion { Question = "What is a computer virus?", Option1 = "Malware that replicates itself", Option2 = "A hardware failure" },
        new QuizQuestion { Question = "What is ransomware?", Option1 = "Malware that demands payment", Option2 = "A spam email" },
        new QuizQuestion { Question = "What should you do with suspicious emails?", Option1 = "Delete them", Option2 = "Reply to verify sender" },
        new QuizQuestion { Question = "What is the purpose of an antivirus?", Option1 = "Detect and remove malware", Option2 = "Protect your privacy" },
        new QuizQuestion { Question = "What does a phishing email often contain?", Option1 = "Urgent requests", Option2 = "Weather updates" },
        new QuizQuestion { Question = "What is a botnet?", Option1 = "A network of compromised computers", Option2 = "A new type of social network" },
        new QuizQuestion { Question = "What is the safest way to share sensitive data?", Option1 = "Using encryption", Option2 = "Sending over public Wi-Fi" },
        new QuizQuestion { Question = "What does social engineering rely on?", Option1 = "Human interaction", Option2 = "Advanced algorithms" },
        new QuizQuestion { Question = "What is a digital signature?", Option1 = "Electronic proof of authenticity", Option2 = "An online autograph" },
        new QuizQuestion { Question = "How often should you update software?", Option1 = "As updates are available", Option2 = "Once a year" },
        new QuizQuestion { Question = "What is a secure password storage method?", Option1 = "Password manager", Option2 = "Sticky notes" },
        new QuizQuestion { Question = "What does 'DoS' stand for?", Option1 = "Denial of Service", Option2 = "Data over Security" },
        new QuizQuestion { Question = "What is a zero-day vulnerability?", Option1 = "A flaw discovered by attackers before a patch", Option2 = "A bug detected on launch day" },
        new QuizQuestion { Question = "What is spyware?", Option1 = "Software that collects information without consent", Option2 = "Software to increase browsing speed" },
        new QuizQuestion { Question = "What is a keylogger?", Option1 = "Software to record keystrokes", Option2 = "An app to log in faster" },
        new QuizQuestion { Question = "What should you avoid clicking on?", Option1 = "Suspicious links in emails", Option2 = "Trusted websites" },
        new QuizQuestion { Question = "What is encryption?", Option1 = "A way to protect data", Option2 = "A method to delete files" },
        new QuizQuestion { Question = "What is brute force hacking?", Option1 = "Guessing passwords by trial and error", Option2 = "Attacking hardware directly" },
        new QuizQuestion { Question = "What is a DDoS attack?", Option1 = "Distributed Denial of Service", Option2 = "Data Decoding and Sorting" },
        new QuizQuestion { Question = "How can you identify a secure website?", Option1 = "It uses HTTPS", Option2 = "It has no advertisements" },
        new QuizQuestion { Question = "What is a trojan horse in cybersecurity?", Option1 = "Malware disguised as legitimate software", Option2 = "A type of email scam" },
        new QuizQuestion { Question = "What is shoulder surfing?", Option1 = "Stealing information by observing someone", Option2 = "A type of online phishing" },
        new QuizQuestion { Question = "What is the main risk of public Wi-Fi?", Option1 = "Man-in-the-middle attacks", Option2 = "Slower internet speed" },
        new QuizQuestion { Question = "What is the role of a cybersecurity analyst?", Option1 = "Protecting systems from cyber threats", Option2 = "Developing software applications" },
        new QuizQuestion { Question = "What is a honeypot in cybersecurity?", Option1 = "A decoy system to lure attackers", Option2 = "A storage system for secure data" },
        new QuizQuestion { Question = "What is the purpose of a CAPTCHA?", Option1 = "To verify human users", Option2 = "To block malicious emails" },
        new QuizQuestion { Question = "What is a spoofing attack?", Option1 = "Impersonating another device or user", Option2 = "Blocking a user's internet" },
        new QuizQuestion { Question = "What is the best way to secure your mobile device?", Option1 = "Use a strong password and enable encryption", Option2 = "Keep it in airplane mode" },
        new QuizQuestion { Question = "What is the purpose of a patch update?", Option1 = "Fix vulnerabilities", Option2 = "Improve battery life" },
        new QuizQuestion { Question = "What is a rootkit?", Option1 = "Malware that hides its presence", Option2 = "A tool to improve performance" },
        new QuizQuestion { Question = "What is SQL injection?", Option1 = "An attack to exploit database vulnerabilities", Option2 = "A programming method" },
        new QuizQuestion { Question = "What does BYOD stand for?", Option1 = "Bring Your Own Device", Option2 = "Build Your Own Database" },
        new QuizQuestion { Question = "What is the safest way to store sensitive documents?", Option1 = "Encrypted storage", Option2 = "Email attachments" },
        new QuizQuestion { Question = "What is the purpose of a backup?", Option1 = "To recover data if lost", Option2 = "To speed up your system" },
        new QuizQuestion { Question = "What is clickjacking?", Option1 = "Tricking users into clicking disguised links", Option2 = "Delaying website loading" },
        new QuizQuestion { Question = "What does GDPR regulate?", Option1 = "Data privacy in Europe", Option2 = "Global product manufacturing" },
        new QuizQuestion { Question = "What is a cyber risk assessment?", Option1 = "Evaluating potential security threats", Option2 = "A survey about internet usage" },
        new QuizQuestion { Question = "What does a digital certificate ensure?", Option1 = "Trust and identity verification", Option2 = "Faster internet browsing" },
        new QuizQuestion { Question = "What is the primary goal of cybersecurity?", Option1 = "To protect data", Option2 = "To block ads" },
        new QuizQuestion { Question = "What is a password?", Option1 = "A security key", Option2 = "A username" },
        new QuizQuestion { Question = "What does an antivirus do?", Option1 = "Stops malware", Option2 = "Speeds up the computer" },
        new QuizQuestion { Question = "What is a phishing scam?", Option1 = "Fake emails to steal info", Option2 = "A fishing game" },
        new QuizQuestion { Question = "What is a computer firewall?", Option1 = "Blocks unauthorized access", Option2 = "A physical barrier" },
        new QuizQuestion { Question = "What does HTTPS indicate?", Option1 = "A secure website", Option2 = "A fast website" },
        new QuizQuestion { Question = "What is a strong password?", Option1 = "Hard to guess", Option2 = "Your name" },
        new QuizQuestion { Question = "What should you do if you see a suspicious email?", Option1 = "Ignore or delete", Option2 = "Reply quickly" },
        new QuizQuestion { Question = "What does a secure Wi-Fi network require?", Option1 = "A password", Option2 = "No password" },
        new QuizQuestion { Question = "What is spam?", Option1 = "Unwanted emails", Option2 = "A type of food" },
        new QuizQuestion { Question = "What does a CAPTCHA verify?", Option1 = "You are human", Option2 = "Your email address" },
        new QuizQuestion { Question = "What is a secure way to store passwords?", Option1 = "Password manager", Option2 = "Notebook" },
        new QuizQuestion { Question = "What is malware?", Option1 = "Harmful software", Option2 = "Hardware issue" },
        new QuizQuestion { Question = "What does a VPN provide?", Option1 = "Secure connection", Option2 = "Faster browsing" },
        new QuizQuestion { Question = "What is a backup?", Option1 = "Copy of data", Option2 = "Old computer" },
        new QuizQuestion { Question = "What is social engineering?", Option1 = "Tricking people", Option2 = "Engineering a building" },
        new QuizQuestion { Question = "What is ransomware?", Option1 = "Malware asking for money", Option2 = "Spam emails" },
        new QuizQuestion { Question = "What is the purpose of encryption?", Option1 = "To protect data", Option2 = "To delete data" },
        new QuizQuestion { Question = "What is spyware?", Option1 = "Tracks your activity", Option2 = "Protects your data" },
        new QuizQuestion { Question = "What is a phishing link?", Option1 = "Fake link to steal info", Option2 = "Link to a website" },
        new QuizQuestion { Question = "What does updating software do?", Option1 = "Fixes bugs", Option2 = "Makes it older" },
        new QuizQuestion { Question = "What is a secure website feature?", Option1 = "Padlock symbol", Option2 = "No images" },
        new QuizQuestion { Question = "What does two-factor authentication require?", Option1 = "Extra verification", Option2 = "Just a username" },
        new QuizQuestion { Question = "What is a public Wi-Fi risk?", Option1 = "Hacking attempts", Option2 = "Slow speed" },
        new QuizQuestion { Question = "What is the best way to secure files?", Option1 = "Encryption", Option2 = "Leaving open" },
        new QuizQuestion { Question = "What is a computer virus?", Option1 = "Harmful program", Option2 = "Software update" },
        new QuizQuestion { Question = "What is clickjacking?", Option1 = "Tricking into clicking", Option2 = "Typing fast" },
        new QuizQuestion { Question = "What is a botnet?", Option1 = "Infected devices network", Option2 = "Gaming platform" },
        new QuizQuestion { Question = "What does 'DoS' mean?", Option1 = "Denial of Service", Option2 = "Data on Screen" },
        new QuizQuestion { Question = "What does a strong password contain?", Option1 = "Numbers and symbols", Option2 = "Just letters" },
        new QuizQuestion { Question = "What does a patch update fix?", Option1 = "Security issues", Option2 = "Screen resolution" },
        new QuizQuestion { Question = "What is the safest way to download software?", Option1 = "From official sites", Option2 = "Any random site" },
        new QuizQuestion { Question = "What is identity theft?", Option1 = "Stealing personal details", Option2 = "Getting a new ID card" },
        new QuizQuestion { Question = "What does an email attachment with '.exe' indicate?", Option1 = "A program file", Option2 = "A document" },
        new QuizQuestion { Question = "What is the safest way to share data?", Option1 = "Encrypted email", Option2 = "Public folder" },
        new QuizQuestion { Question = "What does a hacker try to do?", Option1 = "Access unauthorized data", Option2 = "Fix computers" },
        new QuizQuestion { Question = "What is shoulder surfing?", Option1 = "Stealing info by looking", Option2 = "Typing on your phone" },
        new QuizQuestion { Question = "What should you do with old passwords?", Option1 = "Change them often", Option2 = "Reuse them" },
        new QuizQuestion { Question = "What is brute force hacking?", Option1 = "Guessing passwords", Option2 = "Breaking hardware" },
        new QuizQuestion { Question = "What is the purpose of a cybersecurity audit?", Option1 = "Find vulnerabilities", Option2 = "Design websites" },
        new QuizQuestion { Question = "What is a rootkit?", Option1 = "Hidden malware", Option2 = "A device driver" },
        new QuizQuestion { Question = "What is the safest device lock?", Option1 = "Biometric scan", Option2 = "No lock" },
        new QuizQuestion { Question = "What is phishing?", Option1 = "Scam to steal info", Option2 = "Internet browsing" },
        new QuizQuestion { Question = "What does GDPR protect?", Option1 = "Data privacy", Option2 = "Passwords" }
    };

    public static QuizQuestion GetRandomQuizQuestion => quizQuestions[Random.Range(0,
        quizQuestions.Count)];
}
